## 00. PyTorch Fundamentals

Resource notebook: https://github.com/mrdbourke/pytorch-deep-learning

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using 'torch.Tensor()' : https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [6,7,8]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape # Has one 3 by 3

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [16]:
TENSOR2 = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [6,7,8]],
                        [[10,11,12],
                         [13,14,15],
                         [16,17,18]]])

In [17]:
TENSOR2.ndim

3

In [18]:
TENSOR2.shape

torch.Size([2, 3, 3])

In [19]:
TENSOR2[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [20]:
TENSOR2[1]

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

In [21]:
TENSOR3 = torch.tensor([[[1,2,3,1],
                        [3,4,5,1],
                        [6,7,8,1],
                         [1,2,3,1]],
                        [[10,11,12,1],
                         [13,14,15,1],
                         [16,17,18,1],
                         [10,11,12,1]]])

In [22]:
TENSOR3.ndim

3

In [23]:
TENSOR3.shape

torch.Size([2, 4, 4])

### Random Tensors

Why random tensors?
Random Tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

'Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers'

Torch random tensors: https://pytorch.org/docs/stable/generated/torch.rand.html

In [24]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4618, 0.7484, 0.5211, 0.1312],
        [0.5274, 0.7146, 0.3733, 0.5340],
        [0.3465, 0.9517, 0.3546, 0.1301]])

In [25]:
# Create a random tensor of size (5, 10, 10)
random_tensor2 = torch.rand(5, 10, 10)
random_tensor2

tensor([[[0.7061, 0.0026, 0.3477, 0.6006, 0.9405, 0.9637, 0.3918, 0.8153,
          0.2129, 0.7278],
         [0.2357, 0.4626, 0.8300, 0.0769, 0.8627, 0.1638, 0.8644, 0.2863,
          0.7252, 0.0141],
         [0.8286, 0.2637, 0.8245, 0.4986, 0.6741, 0.5453, 0.5360, 0.2516,
          0.6989, 0.3445],
         [0.8235, 0.3342, 0.4982, 0.8984, 0.1756, 0.1395, 0.2536, 0.6207,
          0.2122, 0.5261],
         [0.8085, 0.5703, 0.5592, 0.4646, 0.4462, 0.4533, 0.7446, 0.5663,
          0.9289, 0.8020],
         [0.1613, 0.6919, 0.7060, 0.7297, 0.4822, 0.3537, 0.2120, 0.3338,
          0.4007, 0.0560],
         [0.5157, 0.9279, 0.4984, 0.4907, 0.0929, 0.2103, 0.3140, 0.0719,
          0.4483, 0.1145],
         [0.8719, 0.7503, 0.0756, 0.4159, 0.6847, 0.8252, 0.6202, 0.7444,
          0.5870, 0.7005],
         [0.6876, 0.8221, 0.9640, 0.3332, 0.1224, 0.7083, 0.2589, 0.1955,
          0.6667, 0.6935],
         [0.2251, 0.2456, 0.6372, 0.8680, 0.9441, 0.3497, 0.9837, 0.0547,
          0.2550,

In [26]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # colour channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeroes and ones

In [27]:
# Create a tensor of all zeroes
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
ones.dtype

torch.float32

In [31]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [32]:
# Use torch.range() and get depracted message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
# tensor of ones same shape as image size tensor
random_image_size_tensor_ones = torch.ones_like(random_image_size_tensor)
random_image_size_tensor_ones

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]]])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 most common issues you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [35]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor, e.g. float32, float16 (default is float32)
                               device="cpu", # what device is your tensor on, can't mix devices when working with tensors
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [36]:
float_32_tensor.dtype

torch.float32

In [37]:
float_16_tensor = float_32_tensor.type(torch.float16) # chamhe datatype of tensor
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [38]:
float_complex_128 = float_32_tensor.type(torch.complex128) # Use of complex numbers representation of tensors
float_complex_128

tensor([3.+0.j, 6.+0.j, 9.+0.j], dtype=torch.complex128)

In [39]:
float_32_tensor*float_complex_128

tensor([ 9.+0.j, 36.+0.j, 81.+0.j], dtype=torch.complex128)

In [40]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [41]:
int_64_tensor = torch.tensor([3, 6, 9], dtype=torch.int64)
int_64_tensor

tensor([3, 6, 9])

In [42]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

In [43]:
float_16_tensor*int_64_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use 'tensor.dtype'
2. Tensors not right shape - to get shape from a tensor, can use 'tensor.shape'
3. Tensors not on the right device - to get device from a tensor, can use 'tensor.device'

In [44]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4486, 0.8877, 0.4877, 0.8261],
        [0.4241, 0.5163, 0.3275, 0.4214],
        [0.0584, 0.4654, 0.0124, 0.2656]])

In [45]:
some_tensor = some_tensor.type(torch.float16) # change datatype to "float16" from "float32"

In [46]:
 # Find out details about some tensor
 print(some_tensor)
 print(f"Datatype of tensor: {some_tensor.dtype}")
 print(f"Shape of tensor: {some_tensor.shape}")
 print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4485, 0.8877, 0.4878, 0.8262],
        [0.4241, 0.5161, 0.3274, 0.4214],
        [0.0584, 0.4653, 0.0124, 0.2656]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [47]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [48]:
# MUltiply tensor by 10 (reassign)
tensor*10

tensor([10, 20, 30])

In [49]:
tensor

tensor([1, 2, 3])

In [50]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [51]:
# Try out PyTorch in-built functions
print(torch.mul(tensor, 10))
print(torch.add(tensor, 10))

tensor([10, 20, 30])
tensor([11, 12, 13])


### Matrix multiplication

Two main ways of performing multiplication in neural netwoks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product of rows and columns)

More information on multiplying matrices:
* https://www.mathsisfun.com/algebra/matrix-multiplying.html
* http://matrixmultiplication.xyz/

There are two main rules performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match (**1st tensor must have same number of columns as number of rows of 2nd tensor**):
* '(3, 2) @ (3, 2)' won't work
* '(2, 3) @ (3, 2)' will work
* '(3, 2) @ (2, 3)' will work
2. The resulting matrix has the shape of the **outer dimensions**:
* '(2, 3) @ (3, 2)' -> '(2, 2)'
* '(3, 2) @ (2, 3)' -> '(3, 3)'

In [52]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.8586, 0.6506],
        [1.1254, 1.1408]])

In [53]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.2291, 0.0772, 0.0708],
        [0.1722, 0.1329, 0.0585],
        [0.3519, 0.1642, 0.1120]])

In [54]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [55]:
# Matrix multiplication
torch.matmul(tensor, tensor) # dot product of row and column (in this case vector so only 1 row and 1 column)

tensor(14)

In [56]:
tensor

tensor([1, 2, 3])

In [57]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [58]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
value

CPU times: user 242 µs, sys: 0 ns, total: 242 µs
Wall time: 248 µs


tensor(14)

In [59]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.74 ms, sys: 0 ns, total: 1.74 ms
Wall time: 2.21 ms


tensor(14)

### One of the most common errors in deep learning: shape errors


In [60]:
 # Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
# torch.matmul(tensor_A, tensor_B) will return a shape error

In [61]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes of dimensions of a given tensor.

In [62]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [63]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [64]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [65]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

## Finding the min, max, mean, sum, etc. (tensor aggregation)


In [66]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [67]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [68]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [69]:
# Find the mean - note: torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [70]:
 # Find the sum
 torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [71]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [72]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [73]:
x[0]

tensor(1)

In [74]:
# Find the position in tensor that has the maximum value with argmax()
torch.argmax(x), torch.max(x)

(tensor(9), tensor(91))

In [75]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keeps the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [76]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [77]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9) # has to equate to the size of the tensor (size of x)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [78]:
# Change the view
z = x.view(1, 9) # x.view(9, 1)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [79]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [80]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # 'dim=0' is stack by row, 'dim=1' is stack by column
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [81]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [82]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (ddimension)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [83]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # (height, width, colour_channels)

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # (colour_channels, height, width)

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [84]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [85]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [86]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [87]:
# Let's index on the middle bracket (dim=1)
x[0][0] # x[0, 0]

tensor([1, 2, 3])

In [88]:
# Let's index on the most inner bracket (last dimension)
x[0][1][1]

tensor(5)

In [89]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [90]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [91]:
# Get all values of the 0th dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [92]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [93]:
# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Date in NumPy, want in PyTorch tensor -> 'torch.from_numpy(ndarray)'
* PyTorch tensor -> NumPy -> 'torch.Tensor.numpy()'

In [94]:
 # NumPy array to tensor
 import numpy as np

 array = np.arange(1.0, 8.0)
 tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
 array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [95]:
# Change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [96]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [97]:
# Change the tensor, what happens to 'numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

In short how a neural network learns:

'start with random numbers -> tensor operations -> update random numbers to try and make them better representaions of the data -> again -> again -> again...'

To reduce teh randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [98]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8782, 0.7191, 0.3892, 0.4374],
        [0.5277, 0.4797, 0.9294, 0.4573],
        [0.4411, 0.8214, 0.7437, 0.3426]])
tensor([[0.4224, 0.8888, 0.0607, 0.4611],
        [0.7231, 0.3860, 0.7582, 0.2551],
        [0.6782, 0.9795, 0.6484, 0.1919]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [99]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 84

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.7865, 0.3806, 0.7820, 0.4943],
        [0.0335, 0.7917, 0.8909, 0.8513],
        [0.4682, 0.0496, 0.4305, 0.5029]])
tensor([[0.7865, 0.3806, 0.7820, 0.4943],
        [0.0335, 0.7917, 0.8909, 0.8513],
        [0.4682, 0.0496, 0.4305, 0.5029]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:

* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good.

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well).
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options... see this post for what option to get: https://timdettmers.com/category/deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/


In [100]:
!nvidia-smi

Tue Jan 23 23:47:45 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [101]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running comute on the GPU or CPUS, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available, else default to CPU

In [102]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [103]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [104]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [105]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [106]:
# If tensor is on GPU, can't transform it to NumPy
# tensor_on_gpu.numpy() will cause error

In [107]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.to("cpu") # cpu().numpy()
tensor_back_on_cpu

tensor([1, 2, 3])

In [108]:
tensor_on_gpu # remains unchanged

tensor([1, 2, 3], device='cuda:0')

## Exercies & Extra-curriculum

##### 1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.

* Documentation on 'torch.Tensor': https://pytorch.org/docs/stable/tensors.html#torch-tensor

* Documentaion on 'torch.cuda': https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics

##### 2. Create a random tensor with shape (7, 7).

In [109]:
tensor = torch.rand(7, 7)
tensor, tensor.shape

(tensor([[0.4388, 0.1109, 0.1284, 0.9631, 0.1101, 0.6563, 0.5408],
         [0.1215, 0.3552, 0.4256, 0.7984, 0.8762, 0.5531, 0.2837],
         [0.1318, 0.8071, 0.8613, 0.2720, 0.1169, 0.5769, 0.0788],
         [0.6099, 0.3372, 0.0969, 0.7764, 0.4854, 0.0933, 0.5805],
         [0.9849, 0.0228, 0.7192, 0.0445, 0.9893, 0.8578, 0.9588],
         [0.3884, 0.2061, 0.5131, 0.9055, 0.6319, 0.3463, 0.4888],
         [0.6637, 0.5971, 0.4773, 0.6868, 0.4333, 0.0781, 0.6251]]),
 torch.Size([7, 7]))

##### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [110]:
tensor2 = torch.rand(1, 7)
X = torch.mm(tensor, tensor2.T)
X, X.shape

(tensor([[1.9333],
         [2.0777],
         [1.4934],
         [1.7740],
         [2.6916],
         [2.1336],
         [1.9809]]),
 torch.Size([7, 1]))

##### 4. Set the random seed to 0 and do exercises 2 & 3 over again.

In [111]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
Y = torch.mm(torch.rand(7, 7), torch.rand(1, 7).T)
Y, Y.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

##### 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [112]:
RANDOM_SEED_GPU = 1234
torch.cuda.manual_seed(RANDOM_SEED_GPU)

##### 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [113]:
torch.manual_seed(1234)
tensor_A = torch.rand(2, 3)
tensor_B = torch.rand(2, 3)
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_A_gpu = tensor_A.to(device)
tensor_B_gpu = tensor_B.to(device)
print(f"Showing original tensors on CPU: \ntensor_A = {tensor_A, tensor_A.device} \ntensor_B = {tensor_B, tensor_B.device}")
print(f"\nShowing tensors moved on to GPU: \ntensor_A_gpu = {tensor_A_gpu, tensor_A_gpu.device} \ntensor_B_gpu = {tensor_B_gpu, tensor_B_gpu.device}")

Showing original tensors on CPU: 
tensor_A = (tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]), device(type='cpu')) 
tensor_B = (tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]]), device(type='cpu'))

Showing tensors moved on to GPU: 
tensor_A_gpu = (tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0'), device(type='cuda', index=0)) 
tensor_B_gpu = (tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0'), device(type='cuda', index=0))


##### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [114]:
result = torch.mm(tensor_A_gpu, tensor_B_gpu.T)
result, result.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

##### 8. Find the maximum and minimum values of the output of 7.

In [115]:
print(f"Maximum value of tensor 'result': {result.max()}")
print(f"Minimum value of tensor 'result': {result.min()}")

Maximum value of tensor 'result': 0.5617256760597229
Minimum value of tensor 'result': 0.3647301495075226


##### 9. Find the maximum and minimum index values of the output of 7.

In [116]:
print(f"Index value of maximum value of tensor 'result': {result.argmax()}")
print(f"INdex value of minimum value of tensor 'result': {result.argmin()}")

Index value of maximum value of tensor 'result': 3
INdex value of minimum value of tensor 'result': 0


##### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [117]:
torch.manual_seed(7)
random_tensor = torch.rand(1, 1, 1, 10)

random_tensor_squeezed = random_tensor.squeeze()

print(f"Original tensor: {random_tensor, random_tensor.shape}")
#print(f"\nShape of original tensor 'random_tensor': {random_tensor.shape}")
print(f"\nOriginal tensor squeezed to remove all 1 dimensions: {random_tensor_squeezed, random_tensor_squeezed.shape}")
#print(f"\nShape of 'random_tensor' squeezed to remove all the 1 dimensions: {random_tensor_squeezed.shape}")

Original tensor: (tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), torch.Size([1, 1, 1, 10]))

Original tensor squeezed to remove all 1 dimensions: (tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), torch.Size([10]))
